### ISSUE TITLE
Can't shrink Image back

### ISSUE THREAD

**Issue by oky1** [akella/pjax#1]
Как закончить анимацию обратно? После прокрутки анимации в обратное состояние получается пустое пространство вокруг картинки, далее  this.done(). Есть ли способ запустить this.done() и после сжать картинку и вернуть на место?

**Comment by akella** [comment]
Там я в стриме говорил, что обратно надо делать по аналогии, но вдобавок нужно запоминать старую позицию скролла чтобы к ней возвращать блок. По шагам это будет так,
1) Вместо полноэкранной картинки накладываем уже элемент слайдера
2) Под ним показываем скролл блок с картинками
3) Меняем размер полноэкранного элемента слайдера до исходного в изначальном слайдере.
4) this.done.

Вобщем-то также как и анимация "туда", только в обратном порядке.
Вот пример этого подхода http://barbajs.org/demo/grid/index.html

**Comment by oky1** [comment]
Спасибо. Я все так и делал. Моя проблема была в zIndex-е.
